#!/usr/bin/env bash

WATCHDIR=~/Downloads

cd "$WATCHDIR" || exit

mkdir -p images videos audio other
mkdir -p documents/docs documents/pdf documents/text documents/project1 documents/project2 documents/project3

inotifywait -mr "$WATCHDIR" -e create -e moved_to -e close_write | while read -r path action file; do

    case "$file" in
        documents|images|videos|audio|other)
            continue
            ;;
    esac

    [ -e "$file" ] || continue

    if [ -d "$file" ]; then
        mv "$file" other/
        continue
    fi

    if [[ "$file" == *project1* ]]; then
        mv "$file" documents/project1/
        continue
    elif [[ "$file" == *project2* ]]; then
        mv "$file" documents/project2/
        continue
    elif [[ "$file" == *project3* ]]; then
        mv "$file" documents/project3/
        continue
    fi

    case "$file" in
        *.jpg|*.jpeg|*.png|*.gif|*.bmp|*.svg)
            mv "$file" images/
            ;;

        *.mp4|*.mkv|*.mov)
            mv "$file" videos/
            ;;

        *.mp3|*.wav|*.ogg|*.flac)
            mv "$file" audio/
            ;;
        
        *.pdf)
            mv "$file" documents/pdf/
            ;;

        *.doc|*.docx|*.odt|*.xls|*.xlsx|*.ppt|*.pptx)
            mv "$file" documents/docs/
            ;;

        *.txt)
            mv "$file" documents/text/
            ;;
 
        *)
            mv "$file" other/
            ;;
    esac
done










    
